spring.application.name=Task1to8

spring.datasource.url=jdbc:h2:file:./data/studentDB

#For specifying what type of driver is to be used. Not necessary for current versions since spring boot auto detects
#spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

#For telling h2  to create proper SQL commands. Not necessary for current versions
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true